name: "CI"
on:
  push:
    branches:
      - develop
permissions:
  id-token: write
  contents: write
  packages: write
jobs:
  main:
    name: Run checks and deploy to beta
    runs-on: ubuntu-18.04
    if: "github.event_name != 'pull_request' || !github.event.pull_request.draft"
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-cast-node16-${{ hashFiles('apps/cast/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-cast-node16-
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run checks
      run: |
        yarn format:check
        yarn lint
        yarn test:config --watchAll=false
        yarn test --watchAll=false
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        role-to-assume: arn:aws:iam::439141495054:role/GithubDeployFrontendRole
        aws-region: us-west-2
    - name: Deploy to beta
      run: |
        echo TODO
